{% set name = "distlib" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3804d0d2d4b5fcd44036eb860cb6660485fcdf5c2aba53dc324d805837ea65b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=68,<75
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - distlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/distlib/
  summary: Distribution utilities
  doc_url: https://pythonhosted.org/distlib/
  dev_url: https://github.com/pypa/distlib
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
    - xylar
